name: Build OpenWrt for Xiaomi MiWiFi Mini
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-23.05
          fetch-depth: 1

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          echo -e "CONFIG_TARGET_ramips=y\nCONFIG_TARGET_ramips_mt7620=y\nCONFIG_TARGET_ramips_mt7620_DEVICE_xiaomi_miwifi-mini=y" > .config
          make defconfig

      - name: Download packages
        run: make download -j8

      - name: Build firmware
        run: make -j$(nproc) || make -j1 V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: bin/targets/ramips/mt7620/*.bin
